TARGET = multiple_loop_test

CPPFLAGS = -g -Wall -std=c++20 -DMULTIPLE_THREAD_SUPPORTS -DUSE_SELECT
CXXFLAGS = -I../include

LDFLAGS =

DEP_LIBS += \
           ../core/libel.a \
           -lpthread

CXX      = g++
RM       = rm -f

TARGET_OBJS = multiple_loop_test.o

%.o : %.cpp
	$(CXX) -c $(CPPFLAGS) $(CXXFLAGS) $<

.PHONY : all clean cleanall rebuild

all: $(TARGET)

$(TARGET) : $(TARGET_OBJS) $(DEP_LIBS)
	$(CXX) -o $(TARGET) $(TARGET_OBJS) $(DEP_LIBS) $(LDFLAGS)

rebuild: clean all

clean:
	@$(RM) *.o *.d

cleanall: clean
	@$(RM) $(TARGET)
