[ req ]
distinguished_name = req_distinguished_name
prompt = no
output_password = 1234

[ req_distinguished_name ]
C = CN
ST = GuangDong
L = ShenZhen
O = Matrixworks
OU = D.I.
CN = Matrixworks Test CA
emailAddress = contact@matrix.works

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
basicConstraints = CA:true
