[ req ]
distinguished_name = req_distinguished_name
prompt = no
output_password = 1234

[ req_distinguished_name ]
C = CN
ST = GuangDong
L = ShenZhen
O = Matrixworks
OU = D.I.
CN = demo-client.matrix.works
emailAddress = contact@matrix.works

[ client ]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
