[ req ]
distinguished_name = req_distinguished_name
prompt = no
output_password = 1234

[ req_distinguished_name ]
C = CN
ST = GuangDong
L = ShenZhen
O = Matrixworks
OU = D.I.
CN = Matrixworks Test Server
emailAddress = contact@matrix.works

[ server ]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = localhost
IP.1 = 127.0.0.1
