
subsystem:
	$(MAKE) -C cdb_api
	$(MAKE) -C db_api
	$(MAKE) -C url_api

clean:
	$(MAKE) -C cdb_api clean
	$(MAKE) -C db_api clean
	$(MAKE) -C url_api clean

cleanall:
	$(MAKE) -C cdb_api cleanall
	$(MAKE) -C db_api cleanall
	$(MAKE) -C url_api cleanall

